### PR TITLE
ML-035/organize controllers

### PR DESCRIPTION
**Pull request by WhatWasThatt**
# Description

add nested attributes for tag
delete excess controllers and actions
fix request specs
fix routing specs
update routes
add home controller for heroku

## Trello card link

https://trello.com/c/wKCfRHjK

# Checklist:

- [x] My code fixes the problem or adds required functionality
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove that my feature works
- [x] New and existing unit tests pass locally with my changes

# Additional requirements:

- [ ] Does your code require any migrations to be ran?
- [ ] Does your code require installing any new gems or system dependencies?
- [ ] Does your code require any changes to current deployment process?

# Additional Information

### CODE REVIEW

**Review by twill11 — APPROVED** [review]
I think that PR is very big, but i approved this, because no new code! gj

**Review by dmitrymalllpr — CHANGES_REQUESTED** [review]
too big, too complicate

**Review by KarinaKlevzhits — APPROVED** [review]

**Review by twill11 — APPROVED** [review]
Nice! Look's better

**Review by twill11 — APPROVED** [review]

**Review by dmitrymalllpr — APPROVED** [review]
Not good for prod BUT approve. Please follow git flow.

**Pull request merged**
